seed: 314
pretrained_model: bert-large-uncased
tokenizer_name: bert-large-uncased
device: mps

datamodule:
  train_path: dataset/train_df_all_english.parquet
  text_col: Translation
  label_col: impact_length_idx
  stratify_col: impact_length_idx
  max_length: 512
  use_cls_weight: True
  batch_size: 8
  test_size: 0.25

model:
  hidden_size: 1024
  num_labels: 3
  classifier_dropout: 0.2

trainer:
  num_epochs: 10
  lr: 1e-4
  weight_decay: 0.01
  warm_up_step: 0.1
