seed: 3407
pretrained_model: nbroad/ESG-BERT
tokenizer_name: nbroad/ESG-BERT
device: cuda

datamodule:
  train_path: Z:/Programing_Space/DataSpell_Workspace/Research_FinMLP Competition/ml-esg-3-main/dataset/train_df_all_english_segmented.parquet
  text_col: Translation
  label_col: impact_length_idx
  stratify_col: impact_length_idx
  max_length: 400
  use_cls_weight: True
  batch_size: 8
  test_size: 0.2

model:
  hidden_size: 768
  num_labels: 3
  classifier_dropout: 0.15
  activation: LeakyReLU

trainer:
  num_epochs: 10
  lr: 1e-04
  weight_decay: 0.01
  warm_up_step: 0.1
